version: '3.8'

services:
  api:
    build: .
    container_name: skillgrid_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/skillgrid
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=skillgrid
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./:/app
    command: >
      bash -c "alembic upgrade head && 
               uvicorn app.main:app --host 0.0.0.0 --port 8000"

  postgres:
    image: postgres:15
    container_name: skillgrid_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-skillgrid}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 